#!/usr/bin/env python

import sys
import ast
from walker import Walker

if __name__ == '__main__':
    filename = sys.argv[1] if len(sys.argv) == 2 else None
    source = sys.stdin.read() if not filename else None

    ast.walk(ast.parse(source, filename), Walker(stream=sys.stdout))
